"""Phase 2 schema

Revision ID: a253d2a67c78
Revises: 7ac5ad76f9d6
Create Date: 2026-02-20 03:13:34.184744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a253d2a67c78'
down_revision = '7ac5ad76f9d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mom', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('attendance_code', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('attendance_code')
        batch_op.drop_column('mom')

    # ### end Alembic commands ###
