"""add attendance inventory wiki tables

Revision ID: f24a9fa687af
Revises: a253d2a67c78
Create Date: 2026-02-20 09:11:25.942516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f24a9fa687af'
down_revision = 'a253d2a67c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('inventory_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('returned_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('request_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('purpose')
        batch_op.drop_column('actual_return_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_return_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('purpose', sa.TEXT(), nullable=True))
        batch_op.alter_column('request_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('returned_at')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('reason')

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
